import { SignIn,useUser,SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import relativeTime from 'dayjs/plugin/relativeTime'
import dayjs from "dayjs";
import LoadingSpinner from "~/components/loading";
import { RouterOutputs, api } from "~/utils/api";
import { useState } from "react";
import { toast } from "react-hot-toast";


dayjs.extend(relativeTime)




const ProfilePage: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="border-x w-full flex flex-col md:max-w-2xl  items-center border-blue-50  ">
        </div>
      </main>
    </>
  )
}

export default ProfilePage;
